Removed external fonts and using web safe fonts
cadentcom/pico-wp-block-theme pull request #13
Opened 2024-02-11 21:43 UTC by ratulkhan74

2024-02-12 16:37 UTC, stratofax commented
@ratulkhan74 can you resolve the merge conflicts on this branch with `dev`? Or do you want me to do that?

2024-02-12 19:23 UTC, ratulkhan74 commented
@stratofax  i have fixed the marge conflicts please check

2024-02-13 17:52 UTC, stratofax commented on theme.json
I think we want a theme.json file, but we can add it back in later

2024-02-13 18:07 UTC, stratofax requested changes
I noted some minor text changes. Please make the updates and notify me. Then, I'll install this in a fresh copy of WordPress and test the site it produces.

2024-02-13 18:07 UTC, stratofax commented on parts/sidebar.html
Does this mean no sidebars for this theme?

2024-02-13 18:07 UTC, stratofax commented on patterns/posts-2-col.php
This could be a useful pattern

2024-02-13 18:07 UTC, stratofax commented on patterns/posts-3-col.php
Also may want to retain this pattern?

2024-02-13 18:07 UTC, stratofax commented on patterns/single-post.php
Something we want to keep?

2024-02-13 18:07 UTC, stratofax commented on readme.txt
> +Contributors: Cadent technologies corp
"Cadent Technologies Corp." is our legal name

2024-02-13 18:07 UTC, stratofax commented on readme.txt
> +Pico wp block WordPress Theme, (C) 2024 Cadent technologies corp
Replace with:

```
Pico WP Block Theme (c) 2024 Cadent Technologies Corp.
```

2024-02-13 18:07 UTC, stratofax commented on readme.txt
> +Pico wp block is distributed under the terms of the GNU GPL.
Change to:

```
The Pico WP Block Theme
```

2024-02-13 18:07 UTC, stratofax commented on readme.txt
> +Poppins Font
Remove this since we aren't using any external fonts please

2024-02-13 18:07 UTC, stratofax commented on readme.txt
> +-- End of DM Sans Font credits --
Remove through line 45

2024-02-13 18:07 UTC, stratofax commented on parts/header.html
I need to install the font to test this code but it looks good from the readthrough

2024-02-13 18:07 UTC, stratofax commented on style.css
> +Theme Name: Pico wp block
Replace:

```
Pico WP Block
```

2024-02-13 18:07 UTC, stratofax commented on style.css
> +Author: Cadent technologies corp
As before:

```
Cadent Technologies Corp.
```

2024-02-13 18:07 UTC, stratofax commented on readme.txt
> +Pico theme is a wordpress block theme
Change to:

```
Pico WP Block is a lightweight WordPress block theme optimized for performance and accessibility
```

2024-02-13 18:07 UTC, stratofax commented on style.css
> +Description: Pico wp block is a wordpress block theme
Please update:

```
Description: Pico WP Block is a lightweight WordPress block theme optimized for performance and accessibility
````

2024-02-13 18:09 UTC, stratofax commented
@ratulkhan74 I requested some minor text changes. Please update the code and notify me so I can install the theme on a fresh copy of WordPress and test it there.

Good job paring the theme files down to the bare essentials. My only concern: perhaps we want to restore **some** of the pattern and template files? But we can do that (if we decide to do so) in a later revision.

2024-02-13 19:31 UTC, ratulkhan74 commented on parts/sidebar.html
For inital theme creation we don't need the sidebar when we will dive in to deep in the development and when we need then we will add the sidebar

2024-02-13 19:35 UTC, ratulkhan74 commented on patterns/posts-2-col.php
we marged our new theme into a old theme branch this pattern was for our old theme and i would like to clear you one thing that is the patterns are component for block theme we can create this component anytime in based on our need

2024-02-13 19:36 UTC, ratulkhan74 commented on patterns/posts-3-col.php
This is also from our old theme repo there is no patterns folder in our new theme we marged our new theme branch onto our old theme branch

2024-02-13 19:39 UTC, ratulkhan74 commented on readme.txt
> +Contributors: Cadent technologies corp
Yeah i used this name  "Cadent Technologies Corp." as theme author name in theme doc

2024-02-13 19:41 UTC, ratulkhan74 commented on readme.txt
> +Pico wp block WordPress Theme, (C) 2024 Cadent technologies corp
The copywrite text has been replaced

2024-02-13 19:43 UTC, ratulkhan74 commented on readme.txt
> +Pico wp block is distributed under the terms of the GNU GPL.
@stratofax where will i make the change?

2024-02-13 19:45 UTC, ratulkhan74 commented on readme.txt
> +Poppins Font
@stratofax  Done

2024-02-13 19:47 UTC, ratulkhan74 commented on style.css
> +Theme Name: Pico wp block
@stratofax  done

2024-02-13 19:48 UTC, ratulkhan74 commented on style.css
> +Author: Cadent technologies corp
@stratofax  Will i make the cheange on author name?

2024-02-13 19:50 UTC, ratulkhan74 commented on readme.txt
> +Pico theme is a wordpress block theme
@stratofax  Done

2024-02-13 19:50 UTC, ratulkhan74 commented on style.css
> +Description: Pico wp block is a wordpress block theme
@stratofax  Done

2024-02-14 15:59 UTC, stratofax requested changes
Please update the text **exactly** as described in the examples provided. 

To save you some time, I've formatted these text strings as code, so you can copy them directly from my comments by clicking on the "two squares" copy button on the right. For example:

```
Copy this code by clicking the "two squares" button on the right -->
```

2024-02-14 15:59 UTC, stratofax commented on parts/footer.html
Nice work!

2024-02-14 15:59 UTC, stratofax commented on readme.txt
>  Contributors: Cadent technologies corp
Please update line 2 as follows (including capitalization and punctuation:

```
Contributors: Cadent Technologies Corp.
```

2024-02-14 15:59 UTC, stratofax commented on readme.txt
> +Pico wp block WordPress Theme, (C) 2024 Cadent technologies corp
Not exactly. Please follow punctuation and capitalization exactly:

```
Pico WP Block Theme &copy; 2024 Cadent Technologies Corp.
```

2024-02-14 15:59 UTC, stratofax commented on readme.txt
> +Pico wp block theme is distributed under the terms of the GNU GPL.
Again, please be consistent with capitalization, like so:

```
Pico WP Block Theme
```

2024-02-14 16:01 UTC, stratofax commented on readme.txt
>  Contributors: Cadent technologies corp
Also, please update Line 1 with Title Case, as follows:

```
=== Pico WP Block Theme ===
```

2024-02-14 16:08 UTC, stratofax commented
Just a few minor details, and then we can merge this!

2024-02-14 18:35 UTC, ratulkhan74 commented
@stratofax changes are done

2024-02-14 19:19 UTC, stratofax requested changes
I've gone through all of the changes I requested, marked the conversations Resolved where appropriate.

2024-02-14 19:19 UTC, stratofax commented on parts/footer.html
> +		<p class="has-text-align-center">Pico WP Block Theme © 2024 Cadent Technologies Corp.</p>
Please delete line 7:

```
<p class="has-text-align-center">Pico WP Block Theme © 2024 Cadent Technologies Corp.</p>
```

Line 6 (above) is preferred, using `&copy;` since this is an HTML file.

2024-02-14 19:19 UTC, stratofax commented on parts/sidebar.html
OK, sounds good! I like simple!

2024-02-14 19:19 UTC, stratofax commented on patterns/posts-2-col.php
I agree, good job!

2024-02-14 19:19 UTC, stratofax commented on patterns/posts-3-col.php
Works for me.

2024-02-14 19:19 UTC, stratofax commented on readme.txt
> +Pico WP Block WordPress Theme, (C) 2024 Cadent technologies corp
For text files, use either "(c)" or Unicode "©"

2024-02-14 19:19 UTC, stratofax commented on readme.txt
> +Pico wp block is distributed under the terms of the GNU GPL.
It looks like you need to change line 21

2024-02-14 19:19 UTC, stratofax commented on readme.txt
> +Pico wp block WordPress Theme, (C) 2024 Cadent technologies corp
Line 20 was not updated with either of the options listed above.

2024-02-14 19:19 UTC, stratofax commented on readme.txt
> +Pico wp block is distributed under the terms of the GNU GPL.
This looks done.

2024-02-14 19:19 UTC, stratofax commented on patterns/single-post.php
I agree we remove as many files as possible. Please keep this as is (deleted).

2024-02-14 19:31 UTC, stratofax approved these changes
Done! Nice work.

2024-02-14 19:32 UTC, merged