Added the theme installation process
cadentcom/pico-wp-block-theme pull request #16
Opened 2024-02-15 20:49 UTC by ratulkhan74

Theme installation process added in the README.md file

2024-02-16 18:45 UTC, stratofax requested changes
I like how you outlined two options, installing using `git clone` and also installing as a ZIP. I don't think we need to tell people how to unzip-install the theme, though.

I made some formatting changes and added some context to explain why you might want to use one approach instead of another. Also, since activating the theme is the same for both installation methods, I separated that out as a new section.

The Installation section should be level 2, all the sub-headings should be level 3.

2024-02-16 18:45 UTC, stratofax commented on README.md
> +### Pico Theme Installation Process in WordPress Theme Local Directory
Please edit this line as follows (this should be a level 2 heading):

```
## Installation
```

2024-02-16 18:45 UTC, stratofax commented on README.md
> +To install the pico theme in wordpress local theme directory flow this steps:
Please edit as follows, using the text between the horizontal rule:

---

To install the Pico WP Block theme, you need a working installation of WordPress. Choose one of the following methods, depending on your configuration.

---

2024-02-16 18:45 UTC, stratofax commented on README.md
> +##### Clone the Theme Repository URL from GitHub
This is now a Level 3 Heading. Rewrite as follows:

```
### Clone the Pico repository from GitHub
```

2024-02-16 18:45 UTC, stratofax commented on README.md
> +##### Clone the Theme Repository URL from GitHub
Markdown formatting for lists:

- add a blank line after headings, paragraphs, and lists. This means that a list (like this numbered list) should have a blank line before & after.
- **DO NOT** start a list (bullet or numbered) with leading spaces. In this case, the GitHub renderer treats your lists as code blocks, not a numbered list.

## To Do for all of your lists

- [x] Add a blank line before & after each list, if it doesn't already exist
- [x] Remove all leading spaces

2024-02-16 18:45 UTC, stratofax commented on README.md
> +    1. Go to the theme repository.
Since you provide the git command and URL, the first few lines aren't required. Please rewrite this section as follows:

----

If you can access the command line on your WordPress server, you can **clone** this repo directly into your `wp-content/themes` directory. This means you can automatically pull the latest version of this theme directly from the repo into your WordPress installation using the `git pull` command.

This repo includes multiple branches with different versions of the theme code:

- The `main` branch includes the **official release** version of the theme, and is the most thoroughly tested. Use this branch for the most stable version of this theme.
- The `dev` branch includes the latest "nightly build" of the pico theme. Use this for the latest features and testing -- not recommended for production environments.

Here's are the  `git clone` command for these branches:

To clone the `main` branch, enter this command:

```
git clone https://github.com/cadentcom/pico-wp-block-theme.git
```

To clone the `dev` branch, enter this command, using the `-b` argument to select the branch:

```
git clone -b dev https://github.com/cadentcom/pico-wp-block-theme.git
```

Follow these steps to use this command on your WordPress server:

1. Open a terminal or command prompt and log into your WordPress server.
2. Use the `cd` command to go to the `themes` directory of your WordPress installation, like this: `cd /path/to/wordpress/wp-content/themes/`
3. To ensure you're in the correct directory, enter `pwd`
4. Enter the `git clone` command you copied above, for either the `main` or `dev` branch. This will clone all the files in this repo to a new directory **inside of** the `themes` directory.

That's it! You just installed the `pico` theme. See the steps below to activate the theme. 

To update the theme at any time, follow the steps listed above, but with the following changes:

1. Open a terminal or command prompt and log into your WordPress server.
2. Use the `cd` command to go to the `pico-wp-block-theme` directory of your WordPress installation, like this: `cd /path/to/wordpress/wp-content/themes/pico-wp-block-theme`
3. Enter `git pull`

Now you've got the latest version of `pico-wp-block-theme` installed on your WordPress server.

---

Please replace the rest of the numbered list in this section with the text above (between the two horizontal rules)

2024-02-16 18:45 UTC, stratofax commented on README.md
> +##### Download the Theme from GitHub and Install by Unzipping
Please add blank lines above and below and rewrite as follows:

```

### Download a ZIP file and install in WordPress

```

2024-02-16 18:45 UTC, stratofax commented on README.md
> +##### Download the Theme from GitHub and Install by Unzipping
Also add the following explanatory text below the new heading, and before the numbered list:

---

If you don't have access to the command line on your WordPress server, or you don't want to mess with `git` commands, you can download a ZIP of this repo and install it in WordPress like any other theme.

Follow these steps to download a ZIP of the entire repo:

----

2024-02-16 18:45 UTC, stratofax commented on README.md
> +    1. Go to the theme repository.
Please rewrite this numbered list as follows:

---

1. In this `pico-wp-block-theme` repo, click on the **Code** tab.
2. Just below the **Code** tab, use the drop-down menu to select the branch you want (usually `main` or `dev`).
3. To the right of the branch selection menu, click the green **Code** button.
4. On the _Local_ tab, click on the **Download ZIP** link at the bottom of the popup.

Now that you've downloaded a ZIP file of the Pico theme, you can install it in WordPress:

1. Log into your WordPress dashboard as an Administrator.
2. Select **Appearance : Themes ** from the left (vertical) menu.
3. Click **Add New Theme**
4. Select the ZIP file you just downloaded and click **OK**.

---

2024-02-16 18:45 UTC, stratofax commented on README.md
> +##### Install the Theme from Admin Panel
Now we can replace this section with a section about activating the theme. Here's our new heading:

```
### Activating the Pico theme
```

2024-02-16 18:45 UTC, stratofax commented on README.md
> +    1. Go to the theme repository.
Please replace this numbered list with the following instructions:

---

After you've installed the pico theme, using either the `git clone` method, or installing it as a ZIP file, you need to activate it. Follow these steps:

1. If you haven't already, log into your WordPress dashboard as an Administrator.
2. Select **Appearance : Themes** from the left (vertical) menu.
3. Mouse over the Pico Theme you just installed.
4. Click the **Activate** button.

---

2024-02-16 20:38 UTC, ratulkhan74 commented
@stratofax All issues are fixed

2024-02-16 20:52 UTC, stratofax requested changes
Some minor, but global, formatting issues:

- Use a single backtick to start and end "in-line" code formatting (on a line with non-code text)
- Use three backticks as a code fence before and after a block of code of one or more lines of code (only).
- No blank lines within lists, only before and after the entire list

See if you can do a global search and replace to fix these issues

2024-02-16 20:52 UTC, stratofax commented on README.md
> +- The ```main``` branch includes the official release version of the theme, and is the most thoroughly tested. Use this branch for the most stable version of this theme.
Three backticks create a "code fence" that indicate the start and finish of a multi-line block of code. When you want to use `code` format inline, just use a single `backtick` character to open and close your `code-styled text`.

2024-02-16 20:52 UTC, stratofax commented on README.md
> +
No blank lines within a list, ordered or unordered. Put the blank lines before and after the list **only**.

2024-02-16 20:52 UTC, stratofax commented on README.md
> +```git clone -b dev https://github.com/cadentcom/pico-wp-block-theme.git```
Since this is a separate line of code, not "in-line," using three backticks is correct. However, you need to add a return after the opening line of the backtick code fence and after each line of code (in this case, just one)

2024-02-17 20:56 UTC, stratofax requested changes
More formatting changes. I was hoping you'd copy and paste most of what I typed in, to avoid these issues, but it seems you may have retyped some of this text. Anyway, I'll publish a comprehensive formatting guide to the Wiki.

Please note that these formatting decisions are not arbitrary, but need to be applied consistently to be effective.

2024-02-17 20:56 UTC, stratofax commented on README.md
> +Here's are the `git clone` command for these branches:
This line has an error that I may have introduced ("Here's are")  and is redundant. Please delete it.

2024-02-17 20:56 UTC, stratofax commented on README.md
> +`git clone https://github.com/cadentcom/pico-wp-block-theme.git`
If this line surrounded with the code fence (three backticks) people can copy it using the copy button on the right.

So, please remove the single backticks and add triple backticks above and below this line so it's easier to copy.

2024-02-17 20:56 UTC, stratofax commented on README.md
> +`git clone -b dev https://github.com/cadentcom/pico-wp-block-theme.git`
Again, please remove the single backticks and add triple backticks above and below this line so it's easier to copy.

2024-02-17 20:56 UTC, stratofax commented on README.md
>  To update the theme at any time, follow the steps listed above, but with the following changes:
I didn't do a good job writing this line. Please replace it as follows:

```
To update the theme at any time, use the `git pull` command, like this:
```

2024-02-17 20:56 UTC, stratofax commented on README.md
> +If you don't have access to the command line on your WordPress server, or you don't want to mess with `git` commands, you can download a **ZIP** of this repo and install it in WordPress like any othe
The word "ZIP" doesn't need to be bold. Please remove the bold formatting, like this:

```
... you can download a ZIP of this repo ...
```

2024-02-17 20:56 UTC, stratofax commented on README.md
>  Follow these steps to download a **ZIP** of the entire repo:
Again, please "un-bold" the word ZIP.

2024-02-17 20:56 UTC, stratofax commented on README.md
> +4. On the *Local tab*, click on the **`Download ZIP`** link at the bottom of the popup.
Here are the formatting rules I'd like us to follow (I'll add these to the wiki later):

- If something is a clickable object (like a button or a link) it should be set as **boldface type**. 
- If it's a name you type in, set it as `code`. 
- If it's a label that appears on the screen, set it as _italics_.

So, **Download ZIP** is a link, and it should be **bold** but not set as code. Please remove the backticks.

2024-02-17 20:56 UTC, stratofax commented on README.md
> +2. Select **`Appearance > Themes`** from the left (vertical) menu.
Based on the rules above:

- The phrase "Select **Appearance : Themes** from the left ..." should be bold, because it's a menu selection. Please remove the backticks.
- Because the ">" (greater than) character is also the closing character for HTML tags, and is often rendered into an escape code sequence, I'd like to avoid it. Simply use the colon (" : ") character instead, as noted in the first bullet.

2024-02-17 20:56 UTC, stratofax commented on README.md
>  4. Select the **ZIP** file you just downloaded and click **OK**.
The word "ZIP" should not be bold, because it's not exactly what you want someone to click, instead it's describing the file type. The word **OK** is correctly boldface because it's the label of the button you need to click.

2024-02-17 20:56 UTC, stratofax commented on README.md
> +2. Select **`Appearance > Themes`** from the left (vertical) menu.
Again: **Appearance : Themes**

- no code backticks
- use the colon (":") instead of the greater than symbol (">")

2024-02-18 19:30 UTC, ratulkhan74 commented
@stratofax Fixing are done

2024-02-18 20:06 UTC, stratofax approved these changes
Well done! Time to commit.

2024-02-18 20:06 UTC, stratofax commented on README.md
> +```
Perfect!

2024-02-18 20:06 UTC, stratofax commented on README.md
> +```
Exactly

2024-02-18 20:08 UTC, merged