All issues are fixed from github list
cadentcom/pico-wp-block-theme pull request #24
Opened 2024-02-20 20:11 UTC by ratulkhan74

@stratofax I have fixed all issues from github list please have a look

2024-02-21 19:33 UTC, stratofax reviewed
@ratulkhan74 Everything looks good, except I noticed that some of the sizing is done in `px` and I'd like to use `rem` as much as possible. Perhaps we can't use `rem` when sizing WordPress block elements, however. Please respond to this on the new Discussion thread: [Sizing: rem vs. em. vs px · cadentcom/pico-wp-block-theme · Discussion #25](https://github.com/cadentcom/pico-wp-block-theme/discussions/25)

While we are still deciding how to handle `rem` vs. `px` outside of the CSS or `theme.json` files, I'm OK with merging this PR. If there's a quick way to switch everything over to `rem` I'd like to do that before we merge, but if it's complicated and may delay us more than one day, let's just merge what you've already committed, and take up the `rem` vs. `px` issue in a new PR.

2024-02-21 19:33 UTC, stratofax commented on templates/page-full-width.html
> +<!-- wp:group {"tagName":"main","style":{"spacing":{"padding":{"top":"20px","bottom":"20px","left":"20px","right":"20px"},"margin":{"top":"20px","bottom":"20px","left":"20px","right":"20px"},"blockGa
My mistake! I said we should use `rem` for font sizes, but I think we should use `rem` for all sizing and dimensions, unless there's a reason not to do so. Please update all the files accordingly.

2024-02-21 19:33 UTC, stratofax commented on templates/page-full-width.html
> +<!-- wp:group {"tagName":"main","style":{"spacing":{"padding":{"top":"20px","bottom":"20px","left":"20px","right":"20px"},"margin":{"top":"20px","bottom":"20px","left":"20px","right":"20px"},"blockGa
See this new discussion for more: [Sizing: rem vs. em. vs px · cadentcom/pico-wp-block-theme · Discussion #25](https://github.com/cadentcom/pico-wp-block-theme/discussions/25)

2024-02-21 19:33 UTC, stratofax commented on templates/page-full-width.html
> +    style="margin-top:20px;margin-right:20px;margin-bottom:20px;margin-left:20px;padding-top:20px;padding-right:20px;padding-bottom:20px;padding-left:20px">
As noted above, please update to `rem` unless these units are required by the WordPress blocks.

2024-02-21 19:39 UTC, stratofax reviewed
Also, I apologize if I missed it, but where is the code for the `meta description` tag?

2024-02-21 22:28 UTC, ratulkhan74 commented
@stratofax [Issue #19](https://github.com/cadentcom/pico-wp-block-theme/issues/19) fixed

2024-02-21 22:33 UTC, ratulkhan74 commented
@stratofax #17 I have created a template file in our theme for the full page layout

2024-02-22 18:55 UTC, stratofax requested changes
I missed this yesterday. The whole point of using Web Safe fonts was to avoid having to download and load font files. Please see #18 for details.

2024-02-22 20:13 UTC, ratulkhan74 commented
@stratofax Header and footer color issue please check #21

2024-02-22 20:32 UTC, stratofax commented
Your original name for this PR, "All issues are fixed from github list" is not a good PR name. I changed it to align with the name of your working branch.

In the future, please avoid adding so many issues to a single branch and PR, as it makes it very hard to merge the branch.

2024-02-22 21:03 UTC, merged

2024-02-22 21:09 UTC, stratofax reviewed
As discussed, we're going to deal with the font issues separately

2024-02-22 21:09 UTC, stratofax commented on theme.json
> +					"fontFamily": "var(--wp--preset--font-family--garamond-regular)",
@ratulkhan74 this is not a good variable name: `--wp--preset--font-family--garamond-regular` because you are using the name of the variable to describe the **value** it contains (in this case, "garamond"). Instead, variables should describe the **purpose** -- in this case, we are using this for headers. So a better name would be something like: `--wp--preset--font-family--header-font`

2024-02-22 21:09 UTC, stratofax commented on theme.json
> +					"fontFamily": "var(--wp--preset--font-family--garamond-regular)",
Again, use a variable name that describes the **purpose** of the variable, not the data it may contain.

2024-02-22 21:09 UTC, stratofax commented on theme.json
> +					"fontFamily": "var(--wp--preset--font-family--garamond-regular)",
Update variable name, as noted earlier.

2024-02-22 21:09 UTC, stratofax commented on theme.json
> +					"fontFamily": "var(--wp--preset--font-family--garamond-regular)",
@ratulkhan74 as discussed, we're going to handle this in another PR, so you can ignore this for now.

2024-02-22 21:09 UTC, stratofax commented on theme.json
> +					"fontFamily": "var(--wp--preset--font-family--garamond-regular)",
@ratulkhan74 as discussed, we're going to handle this in another PR, so you can ignore this for now.

2024-02-22 21:09 UTC, stratofax commented on theme.json
> +					"fontFamily": "var(--wp--preset--font-family--garamond-regular)",
@ratulkhan74 as discussed, we're going to handle this in another PR, so you can ignore this for now.