Issue with fonts
cadentcom/pico-wp-block-theme pull request #29
Opened 2024-02-24 22:09 UTC by ratulkhan74

@stratofax I have created a new branch specily for the fonts issue i have changed the footer font size and discuss the issue in #20 also changed the font family from the theme.json file also removed the fonts file from the assets folder

2024-02-25 17:44 UTC, stratofax commented
@ratulkhan74 This is a good PR: it's for a single issue, it's on a separate branch, and all your changes are related to the issue.

I made some improvements to the PR that I'd like you to do in the future when you create new PRs:

- I changed the name of the PR to be more descriptive. You don't have to mention that the PR is intended to address a specific issue, especially if you follow the next item.
- I linked the PR to the relevant issue using the _Development_ section of the PR sidebar (right side of the page). Note that you can also link an Issue to a PR or a new branch on an Issue page, also using the _Development_ section in the sidebar.
- I assigned the PR to you (again, right hand sidebar, in the _Assignees_ section), because you are the primary coder.
- I assigned myself as the _Reviewer_ (right hand sidebar), since that's my role in this PR.

These are the essential changes I made to the PR that I'd like you to make in the future when you create a new PR.

There are some other updates that are good to add to a PR, using the sections in the right-hand sidebar:

- _Labels:_ right now we don't have a lot of issues and PRs, but as the numbers increase, these labels become more useful. I labeled this PR as an **enhancement** because it's a change or improvement to the code -- an "upgrade" -- but it's not intended to fix an error or a bug. Note that you can assign multiple labels to a PR.
- _Projects:_ as this project becomes more complex, we'll want to take advantage of GitHub's built-in project tracking tools. In many cases, GitHub will automatically update the Status of a related Issue when the linked PR is closed.

Please use these sections in the right-hand sidebar, for both Issues and PRs, to help us track and organize our work.

2024-02-25 18:17 UTC, stratofax commented
The font-family specification should look like this:

```
Garamond, Georgia, Times New Roman, Times, serif
```

2024-02-25 18:26 UTC, stratofax requested changes
Good names describe the **function** or the **purpose** of the variable or element or even the PR or the issue. 

Also, use the DRY principle whenever possible: Don't Repeat Yourself. Don't specify the same formatting in two places when you can do it in one. Don't specify formatting in a block or a paragraph when you can specify it in the "theme.json" file.

2024-02-25 18:26 UTC, stratofax commented on patterns/footer.php
> +        <!-- wp:paragraph {"align":"center","style":{"elements":{"link":{"color":{"text":"var:preset|color|white"}}},"typography":{"fontSize":"0.875rem"}},"textColor":"white"} -->
My preference would be to set the sizes and colors in theme.json instead of in the blocks themselves.

2024-02-25 18:26 UTC, stratofax commented on patterns/footer.php
> +        <p class="has-text-align-center has-white-color has-text-color has-link-color" style="font-size:0.875rem">
These settings seem to duplicate the style settings for the containing block. If we can't set these values in the `theme.json` file, then pick one place to set them in the footer code.

2024-02-25 18:26 UTC, stratofax commented on theme.json
> +					"fontFamily": "Georgia, Palatino, Baskerville, Helvetica, Trebuchet MS, Times New Roman,Garamond",
This font famil specification makes no sense. You're just throwing in all the Web Safe fonts, in no particular order.

The font list should be ordered as follows:

1. The font you **want** to use, if available. In this case, "Garamond"
2. If the first choice isn't available, fall back to the next option, in this case, "Georgia".
3. Continue with additional "fall-back" choices. For serif fonts, this usually includes "Times" and "Times New Roman"
4. Finally, if none of these fonts are available, you can always count on "serif"

For more information on how to specify a [font-family, see the MDN page](https://developer.mozilla.org/en-US/docs/Web/CSS/font-family).

Under no circumstances would you want a sans-serif font, like Helvetica, in a list of serif fonts.

Here's the font-family spec you should use:

```
Garamond, Georgia, Times New Roman, Times, serif
```

2024-02-25 18:26 UTC, stratofax commented on theme.json
> +					"name": "Pico Theme Added Font",
This name is no good, because it doesn't describe the **reason** that we created the font specification.

- We know it's part of the Pico Theme, so having that in the name doesn't help at all
- The fact that it's "Added" is not that informative, either. If we add another font family specification, what are we going to call it? "Another Added Font"? Not useful

Instead, short and descriptive:

```
Serif Font
```

This name describes the **type** of font in the font family.

Another option is to describe the **purpose** of the font, like this:

```
header font
```

Or:

```
Decorative Font
```

For now, let's just go with `Serif Font`

2024-02-25 18:26 UTC, stratofax commented on theme.json
> +					"slug": "pico-theme-added-font"
Please update the slug to match the descriptive name:

```
serif-font
```

2024-02-25 18:26 UTC, stratofax commented on theme.json
> +					"fontFamily": "var(--wp--preset--font-family--pico-theme-added-font)",
Insert new, descriptive slug name

2024-02-25 18:26 UTC, stratofax commented on theme.json
> +					"fontFamily": "var(--wp--preset--font-family--pico-theme-added-font)",
Insert new, descriptive slug name

2024-02-25 18:26 UTC, stratofax commented on theme.json
> +					"fontFamily": "var(--wp--preset--font-family--pico-theme-added-font)",
Insert new, descriptive slug name

2024-02-25 18:44 UTC, stratofax commented on theme.json
> +					"fontFamily": "Georgia, Palatino, Baskerville, Helvetica, Trebuchet MS, Times New Roman,Garamond",
Note that I provided this font spec several days ago, here: https://github.com/cadentcom/pico-wp-block-theme/issues/18#issuecomment-1960064207

2024-02-25 20:45 UTC, ratulkhan74 commented on patterns/footer.php
> +        <!-- wp:paragraph {"align":"center","style":{"elements":{"link":{"color":{"text":"var:preset|color|white"}}},"typography":{"fontSize":"0.875rem"}},"textColor":"white"} -->
@stratofax our global settings already set in theme.json file but in the footer our text is smaller then our body text so if we need to change any specifice block than we have to changed from the block.

2024-02-25 20:48 UTC, ratulkhan74 commented on patterns/footer.php
> +        <p class="has-text-align-center has-white-color has-text-color has-link-color" style="font-size:0.875rem">
@stratofax This way block theme works.

2024-02-25 21:02 UTC, ratulkhan74 commented on theme.json
> +					"name": "Pico Theme Added Font",
@stratofax Because of this issue wordpress use the naming this way `garamond-regular`. But i have used the name you suggested `Serif Font` actually to be honest this naming no making sense for me

2024-02-25 21:02 UTC, ratulkhan74 commented on theme.json
> +					"slug": "pico-theme-added-font"
@stratofax Done

2024-02-26 00:51 UTC, stratofax commented on theme.json
> +					"name": "Pico Theme Added Font",
No worries, I hope it starts to make sense, but I appreciate that you made the changes I recommended.

2024-02-26 00:52 UTC, stratofax commented on patterns/footer.php
> +        <!-- wp:paragraph {"align":"center","style":{"elements":{"link":{"color":{"text":"var:preset|color|white"}}},"typography":{"fontSize":"0.875rem"}},"textColor":"white"} -->
OK, I'm still learning the nuances of coding a block theme.

2024-02-26 00:54 UTC, stratofax reviewed
I just need to install this branch in WordPress and check your code when it's installed. I think I'll be able to approve it after that test.

2024-02-27 19:11 UTC, ratulkhan74 commented
> I just need to install this branch in WordPress and check your code when it's installed. I think I'll be able to approve it after that test.

okay

2024-02-28 16:56 UTC, stratofax commented
As noted, PR #31 includes all the commits in this PR, plus the new ones you added around the Meta Description, so I'll close this PR without merging, and instead focus on merging #31 instead, since it contains all of the changes in this PR.

2024-02-28 16:56 UTC, closed without merging